[project]
name = "simple-wheather-app"
version = "0.1.0"
description = "A Basic wheather app"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jinja2>=3.1.5",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "requests>=2.32.3",
    "shiny>=1.2.1",
    "shinywidgets>=0.5.1",
]
