services:
  shiny_app:
    build:
      context: .
    container_name: shiny-app
    image: local/eoda-dev/starlette-routes-modular
    # image: ghcr.io/eoda-dev/starlette-routes-modular:latest
    pull_policy: always
    ports:
      - "3333:3333"
    restart: always
