services:
  nginx:
    image: nginx:latest
    depends_on: 
      - shiny_app
    ports:
      - "8080:80"
    volumes:
      - ./files/nginx.conf:/etc/nginx/nginx.conf:ro
  shiny_app:
    build:
      context: .
    image: local/eoda-dev/basic-app:latest
    restart: always
    deploy:
      replicas: 3
